# =============================================================================
# ONE STUDIO TASK - Flutter Application Configuration
# =============================================================================
# A comprehensive food ordering and delivery application built for One Studio company
# Features: Menu browsing, item customization, cart management, checkout process
# =============================================================================

name: one_studio_task
description: A Flutter food ordering application for One Studio company
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # iOS-style icons for Cupertino widgets

  # =============================================================================
  # STATE MANAGEMENT & ARCHITECTURE
  # =============================================================================
  flutter_bloc: ^9.1.0  # BLoC pattern for predictable state management
  equatable: ^2.0.7     # Value equality for BLoC states and events
  dartz: ^0.10.1        # Functional programming utilities for error handling

  # =============================================================================
  # DEPENDENCY INJECTION
  # =============================================================================
  get_it: ^8.0.2        # Service locator for dependency injection and singleton management

  # =============================================================================
  # UI COMPONENTS & THEMING
  # =============================================================================
  flutter_screenutil: ^5.9.3          # Responsive UI scaling across devices
  flutter_animate: ^4.5.2             # Rich animation utilities and effects
  shimmer: ^3.0.0                     # Loading shimmer effects for better UX
  flutter_svg: ^2.0.16                # SVG vector graphics rendering
  cached_network_image: ^3.4.1        # Efficient cached network image loading
  be_widgets: ^1.2.1                  # Custom UI widget library
  mobkit_dashed_border: ^0.0.7        # Dashed border widgets for forms
  sliding_up_panel: ^2.0.0+1          # Sliding panel UI for bottom sheets


  # =============================================================================
  # LOCAL DATA STORAGE
  # =============================================================================
  hive: ^2.0.4                        # Lightweight NoSQL local database
  hive_flutter: ^1.1.0                # Flutter integration for Hive storage
  path_provider: ^2.1.5               # File system access for local storage
  path: ^1.9.0                        # Path manipulation utilities

  # =============================================================================
  # UTILITIES & HELPERS
  # =============================================================================
  intl: ^0.20.2                       # Internationalization and localization
  haptic_feedback: ^0.5.1+1           # Haptic feedback for user interactions
  uuid: ^4.5.1                        # UUID generation for unique identifiers
  internet_connection_checker_plus: ^2.7.1  # Internet connectivity monitoring

  # =============================================================================
  # DEVELOPMENT & BUILD TOOLS
  # =============================================================================
  flutter_dotenv: ^6.0.0              # Environment variables management
  flutter_rating_bar: ^4.0.1          # Rating bar widget for reviews


# =============================================================================
# DEVELOPMENT DEPENDENCIES
# =============================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter  # Flutter testing framework
  flutter_localizations:
    sdk: flutter  # Internationalization support
  flutter_lints: ^6.0.0  # Linting rules for code quality
  build_runner: ^2.1.2   # Code generation runner
  hive_generator: ^2.0.1 # Hive code generation for type adapters

# =============================================================================
# FLUTTER CONFIGURATION
# =============================================================================
flutter:
  uses-material-design: true  # Enable Material Design components
  generate: true             # Enable code generation for localization

  # =============================================================================
  # ASSET MANAGEMENT
  # =============================================================================
  assets:
    - assets/fonts/          # Custom font files (Tajawal family)
    - assets/icons/          # SVG icons for UI components
    - assets/images/         # PNG/JPG images and logos
    - assets/translation/    # Localization files (ARB format)
    - env/.env               # Environment variables file
    - assets/json/          # Meals images

  # =============================================================================
  # CUSTOM FONT CONFIGURATION
  # =============================================================================
  fonts:
    - family: Commissioner  # Primary font family for the app
      fonts:
        - asset: assets/fonts/commissioner/Commissioner-Thin.ttf
          weight: 100  # Thin weight
        - asset: assets/fonts/commissioner/Commissioner-ExtraLight.ttf
          weight: 200  # Extra light weight
        - asset: assets/fonts/commissioner/Commissioner-Light.ttf
          weight: 300  # Light weight
        - asset: assets/fonts/commissioner/Commissioner-Regular.ttf
          weight: 400  # Regular weight (default)
        - asset: assets/fonts/commissioner/Commissioner-Medium.ttf
          weight: 500  # Medium weight
        - asset: assets/fonts/commissioner/Commissioner-SemiBold.ttf
          weight: 600  # Semi bold weight
        - asset: assets/fonts/commissioner/Commissioner-Bold.ttf
          weight: 700  # Bold weight
        - asset: assets/fonts/commissioner/Commissioner-ExtraBold.ttf
          weight: 800  # Extra bold weight
        - asset: assets/fonts/commissioner/Commissioner-Black.ttf
          weight: 900  # Black weight
    - family: IrishGrover  # Secondary font family for the app
      fonts:
        - asset: assets/fonts/irish_grover/IrishGrover-Regular.ttf
          weight: 400  # Regular weight